version: '3.9'

services:
  flask_app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask_app
    volumes:
      - ~/.uploads/images/flask:/app/app/static/upload
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - '8080:8080'
